# Generated by Django 2.1.1 on 2018-10-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_com_user', models.CharField(max_length=100)),
                ('_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImgData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_imgs', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParsingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('_total', models.IntegerField(blank=True, null=True)),
                ('_profile_img', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_link', models.URLField()),
                ('_place', models.CharField(blank=True, max_length=100, null=True)),
                ('_time', models.DateField()),
                ('_like', models.IntegerField(blank=True, null=True)),
                ('_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsed_data.ParsingData')),
            ],
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_vidoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsed_data.UploadData')),
            ],
        ),
        migrations.AddField(
            model_name='imgdata',
            name='_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsed_data.UploadData'),
        ),
        migrations.AddField(
            model_name='comment',
            name='_comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsed_data.UploadData'),
        ),
    ]
