# Generated by Django 2.1.1 on 2018-10-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20181002_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='_com_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
