# Generated by Django 2.1.1 on 2018-10-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_auto_20181002_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='_com_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsingdata',
            name='_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uploaddata',
            name='_place',
            field=models.TextField(blank=True, null=True),
        ),
    ]
