# Generated by Django 2.1.1 on 2018-10-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_auto_20181003_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdata',
            name='_imgs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
