# Generated by Django 2.1.1 on 2018-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0006_auto_20181003_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='_time',
            field=models.TextField(),
        ),
    ]
