# Generated by Django 2.1.1 on 2018-10-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0007_auto_20181003_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_com_user',
            new_name='com_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='_comm',
            new_name='comm',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='imgdata',
            old_name='_imgs',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='imgdata',
            old_name='_list_img',
            new_name='list_img',
        ),
        migrations.RenameField(
            model_name='parsingdata',
            old_name='_id',
            new_name='ids',
        ),
        migrations.RenameField(
            model_name='parsingdata',
            old_name='_profile_img',
            new_name='profile_img',
        ),
        migrations.RenameField(
            model_name='parsingdata',
            old_name='_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='uploaddata',
            old_name='_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='uploaddata',
            old_name='_like',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='uploaddata',
            old_name='_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='uploaddata',
            old_name='_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='uploaddata',
            old_name='_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='uploaddata',
            old_name='_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='videodata',
            old_name='_list_video',
            new_name='list_video',
        ),
        migrations.RenameField(
            model_name='videodata',
            old_name='_vidoes',
            new_name='vidoes',
        ),
    ]
