# Generated by Django 2.1.2 on 2018-10-27 23:10

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0011_wordstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bayesian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_list', django.contrib.postgres.fields.hstore.HStoreField()),
                ('blink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsed_data.UploadData')),
            ],
        ),
    ]
