# Generated by Django 2.1.2 on 2018-10-27 23:18

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0012_bayesian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayesian',
            name='data_list',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
