# Generated by Django 2.1.2 on 2018-11-01 05:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0013_auto_20181028_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('video_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('map_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatBotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chat_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
